# Workflow runs when a matching version tag is pushed.

name: Publish Guard Clauses NuGet Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish-guard-clauses-nuget-package:
    # ↓ Change this to "false" to disable the workflow without any alert messages.
    if: ${{ true }}
    # ↑ Change to "true" (or delete) to enable the workflow.

    name: Publish Guard Clauses NuGet package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # enable GitHub OIDC token issuance

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d
        with:
          global-json-file: global.json

      - name: Build and pack
        run: dotnet build ./src/GuardClauses/GuardClauses.csproj --configuration Release

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet Push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push _artifacts/package/release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create GitHub Release
        uses: anton-yurchenko/git-release@ec9c5b5c36b27eaffc628785b9183eae54601200
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
